import { MenuSection } from './types';

export const menuData: MenuSection = {
  '文件': [
    { label: '新建', shortcut: 'Ctrl+N', action: 'new' },
    { label: '新建窗口', shortcut: 'Ctrl+Shift+N', action: 'newWindow' },
    { type: 'separator' },
    { label: '打开...', shortcut: 'Ctrl+O', action: 'open' },
    { label: '打开文件夹...', action: 'openFolder' },
    { label: '快速打开...', shortcut: 'Ctrl+P', action: 'quickOpen' },
    { label: '打开最近文件', submenu: true },
    { type: 'separator' },
    { label: '保存', shortcut: 'Ctrl+S', action: 'save' },
    { label: '另存为...', shortcut: 'Ctrl+Shift+S', action: 'saveAs' },
    { label: '移动到...', action: 'moveTo' },
    { label: '保存全部打开的文件...', action: 'saveAll' },
    { type: 'separator' },
    { label: '导入...', action: 'import' },
    { label: '导出', submenu: true },
    { type: 'separator' },
    { label: '打印...', shortcut: 'Alt+Shift+P', action: 'print', hidden: true },
    { type: 'separator' },
    { label: '属性', action: 'properties' },
    { label: '偏好设置...', shortcut: 'Ctrl+,', action: 'preferences', hidden: true },
  ],
  '编辑': [
    { label: '撤销', shortcut: 'Ctrl+Z', action: 'undo' },
    { label: '重做', shortcut: 'Ctrl+Y', action: 'redo' },
    { type: 'separator' },
    { label: '剪切', shortcut: 'Ctrl+X', action: 'cut' },
    { label: '复制', shortcut: 'Ctrl+C', action: 'copy' },
    { label: '粘贴', shortcut: 'Ctrl+V', action: 'paste' },
    { label: '拼贴图片', action: 'pasteImage' },
    { type: 'separator' },
    { label: '复制为纯文本', action: 'copyPlain' },
    { label: '复制为 Markdown', shortcut: 'Ctrl+Shift+C', action: 'copyMd' },
    { label: '复制为 HTML 代码', action: 'copyHtml' },
    { label: '复制为其他格式', submenu: true },
    { type: 'separator' },
    { label: '粘贴为文本', shortcut: 'Ctrl+Shift+V', action: 'pastePlain' },
    { type: 'separator' },
    { label: '选择', submenu: true },
    { type: 'separator' },
    { label: '删除', submenu: true },
    { type: 'separator' },
    { label: '查找替换', submenu: true },
    { type: 'separator' },
    { label: '数字工具', submenu: true },
    { label: '智能标点', submenu: true },
    { label: '换行符', submenu: true },
    { label: '拼写检查...', action: 'spellCheck' },
    { type: 'separator' },
    { label: '查找对应模块', shortcut: 'Ctrl+Shift+L', action: 'findBlock' },
    { label: '表情与符号', shortcut: 'Win键+句号', action: 'emoji' },
  ],
  '段落': [
    { label: '一级标题', shortcut: 'Ctrl+1', action: 'h1' },
    { label: '二级标题', shortcut: 'Ctrl+2', action: 'h2' },
    { label: '三级标题', shortcut: 'Ctrl+3', action: 'h3' },
    { label: '四级标题', shortcut: 'Ctrl+4', action: 'h4' },
    { label: '五级标题', shortcut: 'Ctrl+5', action: 'h5' },
    { label: '六级标题', shortcut: 'Ctrl+6', action: 'h6' },
    { type: 'separator' },
    { label: '段落', shortcut: 'Ctrl+0', action: 'paragraph' },
    { type: 'separator' },
    { label: '提升标题级别', shortcut: 'Ctrl+=', action: 'increaseHeading' },
    { label: '降低标题级别', shortcut: 'Ctrl+-', action: 'decreaseHeading' },
    { type: 'separator' },
    { label: '表格', submenu: true },
    { label: '公式块', shortcut: 'Ctrl+Shift+M', action: 'mathBlock' },
    { label: '代码块', shortcut: 'Ctrl+Shift+K', action: 'codeBlock' },
    { label: '代码工具', submenu: true },
    { label: '警告框', submenu: true },
    { label: '引用', shortcut: 'Ctrl+Shift+Q', action: 'quote' },
    { type: 'separator' },
    { label: '有序列表', shortcut: 'Ctrl+Shift+[', action: 'orderedList' },
    { label: '无序列表', shortcut: 'Ctrl+Shift+]', action: 'unorderedList' },
    { label: '任务列表', shortcut: 'Ctrl+Shift+X', action: 'taskList' },
    { label: '任务状态', submenu: true },
    { label: '列表缩进', submenu: true },
    { type: 'separator' },
    { label: '在上方插入段落', action: 'insertAbove' },
    { label: '在下方插入段落', action: 'insertBelow' },
    { type: 'separator' },
    { label: '链接引用', action: 'linkReference' },
    { label: '脚注', action: 'footnote' },
    { type: 'separator' },
    { label: '水平分割线', action: 'hr' },
    { label: '内容目录', action: 'toc' },
    { label: 'YAML Front Matter', action: 'yaml' },
  ],
  '格式': [
    { label: '加粗', shortcut: 'Ctrl+B', action: 'bold' },
    { label: '斜体', shortcut: 'Ctrl+I', action: 'italic' },
    { label: '下划线', shortcut: 'Ctrl+U', action: 'underline' },
    { label: '代码', shortcut: 'Ctrl+Shift+`', action: 'inlineCode' },
    { type: 'separator' },
    { label: '删除线', shortcut: 'Alt+Shift+5', action: 'strikethrough' },
    { label: '注释', action: 'comment' },
    { type: 'separator' },
    { label: '超链接', shortcut: 'Ctrl+K', action: 'link', hidden: true },
    { label: '链接操作', submenu: true, hidden: true },
    { label: '图像', submenu: true },
    { type: 'separator' },
    { label: '清除样式', shortcut: 'Ctrl+\\', action: 'clearFormat' },
  ],
  '视图': [
    { label: '显示 / 隐藏侧边栏', shortcut: 'Ctrl+Shift+L', action: 'toggleSidebar' },
    { label: '大纲', shortcut: 'Ctrl+Shift+1', action: 'showOutline' },
    { label: '文档列表', shortcut: 'Ctrl+Shift+2', action: 'showDocs' },
    { label: '文件树', shortcut: 'Ctrl+Shift+3', action: 'showFiles' },
    { label: '搜索', shortcut: 'Ctrl+Shift+F', action: 'showSearch' },
    { type: 'separator' },
    { label: '源代码模式', shortcut: 'Ctrl+/', action: 'sourceMode' },
    { label: '分栏模式', action: 'splitMode' },
    { label: '预览模式', action: 'previewMode' },
    { type: 'separator' },
    { label: '专注模式', shortcut: 'F8', action: 'focusMode' },
    { label: '打字机模式', shortcut: 'F9', action: 'typewriterMode' },
    { label: '显示状态栏', action: 'statusBar' },
    { type: 'separator' },
    { label: '切换全屏', shortcut: 'F11', action: 'fullscreen' },
    { label: '保持窗口在最前端', action: 'alwaysOnTop' },
    { type: 'separator' },
    { label: '实际大小', shortcut: 'Ctrl+Shift+9', action: 'actualSize' },
    { label: '放大', shortcut: 'Ctrl+Shift+=', action: 'zoomIn' },
    { label: '缩小', shortcut: 'Ctrl+Shift+-', action: 'zoomOut' },
    { type: 'separator' },
    { label: '开发者工具', shortcut: 'Shift+F12', action: 'devTools' },
  ],
  '主题': [
    { label: 'Github', action: 'themeGithub' },
    { label: 'Newsprint', action: 'themeNewsprint' },
    { label: 'Night', action: 'themeNight' },
    { label: 'Pixyll', action: 'themePixyll' },
    { label: 'Whitey', action: 'themeWhitey' },
  ],
  '帮助': [
    { label: "What's New...", action: 'whatsNew', hidden: true },
    { type: 'separator' },
    { label: 'Quick Start', action: 'quickStart', hidden: true },
    { label: 'Markdown Reference', action: 'mdReference' },
    { label: 'Install and Use Pandoc', action: 'pandoc', hidden: true },
    { label: 'Custom Themes', action: 'customThemes', hidden: true },
    { label: 'Use Images in Typora', action: 'useImages', hidden: true },
    { label: 'Data Recovery and Version Control', action: 'dataRecovery', hidden: true },
    { label: 'More Topics...', action: 'moreTopics', hidden: true },
    { type: 'separator' },
    { label: '鸣谢', action: 'thanks', hidden: true },
    { label: '更新日志', action: 'changelog', hidden: true },
    { label: '隐私条款', action: 'privacy', hidden: true },
    { label: '官方网站', action: 'website', hidden: true },
    { label: '反馈', action: 'feedback', hidden: true },
    { type: 'separator' },
    { label: '检查更新...', action: 'checkUpdate', hidden: true },
    { label: '我的许可证...', action: 'myLicense', hidden: true },
    { label: '关于', action: 'about' },
  ],
};
