import { MenuSection } from './types';

export const menuData: MenuSection = {
  '文件': [
    { label: '新建文稿', shortcut: '⌘N', action: 'new' },
    { label: '新建窗口', shortcut: '⇧⌘N', action: 'newWindow' },
    { type: 'separator' },
    { label: '打开文件', shortcut: '⌘O', action: 'open' },
    { label: '打开文件夹', shortcut: '⇧⌘O', action: 'openFolder' },
    { type: 'separator' },
    { label: '保存', shortcut: '⌘S', action: 'save' },
    { label: '另存为', shortcut: '⇧⌘S', action: 'saveAs' },
    { label: '在访达中显示', action: 'openCurrentLocation' },
    { type: 'separator' },
    {
      label: '导出',
      submenu: true,
      children: [
        { label: '导出为 PDF', action: 'exportPdf' },
        { label: '导出为 Word (.docx)', action: 'exportDocx' },
        { label: '导出为 HTML', action: 'exportHtml' },
        { label: '导出为 PNG 图像', action: 'exportPng' },
      ],
    },
    { type: 'separator' },
    { label: '关闭文稿', shortcut: '⌘W', action: 'closeDocument' },
  ],
  '编辑': [
    { label: '撤销', shortcut: '⌘Z', action: 'undo' },
    { label: '重做', shortcut: '⇧⌘Z', action: 'redo' },
    { type: 'separator' },
    { label: '剪切', shortcut: '⌘X', action: 'cut' },
    { label: '复制', shortcut: '⌘C', action: 'copy' },
    { label: '粘贴', shortcut: '⌘V', action: 'paste' },
    { label: '粘贴并匹配样式', shortcut: '⇧⌘V', action: 'pastePlain' },
    { type: 'separator' },
    { label: '全选', shortcut: '⌘A', action: 'selectAll' },
    { type: 'separator' },
    {
      label: '查找与替换',
      submenu: true,
      children: [
        { label: '查找', shortcut: '⌘F', action: 'showSearch' },
        { label: '替换', shortcut: '⌘H', action: 'showReplace' },
      ],
    },
    {
      label: '复制为',
      submenu: true,
      children: [
        { label: '纯文本', action: 'copyPlain' },
        { label: 'Markdown', shortcut: '⇧⌘C', action: 'copyMd' },
        { label: 'HTML', action: 'copyHtml' },
      ],
    },
  ],
  '插入': [
    { label: '链接', shortcut: '⌘K', action: 'link' },
    { type: 'separator' },
    { label: '代码块', shortcut: '⇧⌘K', action: 'codeBlock' },
    { label: '公式块', shortcut: '⇧⌘M', action: 'mathBlock' },
    { label: '引用', shortcut: '⇧⌘Q', action: 'quote' },
    { type: 'separator' },
    { label: '有序列表', shortcut: '⇧⌘[', action: 'orderedList' },
    { label: '无序列表', shortcut: '⇧⌘]', action: 'unorderedList' },
    { label: '任务列表', shortcut: '⇧⌘X', action: 'taskList' },
    { type: 'separator' },
    { label: '水平分割线', action: 'hr' },
    { label: '脚注', action: 'footnote' },
    { label: '链接引用', action: 'linkReference' },
    { label: '内容目录', action: 'toc' },
    { label: 'YAML Front Matter', action: 'yaml' },
  ],
  '格式': [
    { label: '粗体', shortcut: '⌘B', action: 'bold' },
    { label: '斜体', shortcut: '⌘I', action: 'italic' },
    { label: '下划线', shortcut: '⌘U', action: 'underline' },
    { label: '删除线', shortcut: '⌥⇧5', action: 'strikethrough' },
    { label: '行内代码', shortcut: '⇧⌘`', action: 'inlineCode' },
    { type: 'separator' },
    {
      label: '段落样式',
      submenu: true,
      children: [
        { label: '正文', shortcut: '⌘0', action: 'paragraph' },
        { label: '一级标题', shortcut: '⌘1', action: 'h1' },
        { label: '二级标题', shortcut: '⌘2', action: 'h2' },
        { label: '三级标题', shortcut: '⌘3', action: 'h3' },
        { label: '四级标题', shortcut: '⌘4', action: 'h4' },
        { label: '五级标题', shortcut: '⌘5', action: 'h5' },
        { label: '六级标题', shortcut: '⌘6', action: 'h6' },
      ],
    },
    {
      label: '标题级别',
      submenu: true,
      children: [
        { label: '提升标题级别', shortcut: '⌘=', action: 'increaseHeading' },
        { label: '降低标题级别', shortcut: '⌘-', action: 'decreaseHeading' },
      ],
    },
    { type: 'separator' },
    { label: '清除格式', shortcut: '⌘\\', action: 'clearFormat' },
  ],
  '视图': [
    { label: '编辑模式', shortcut: '⌘/', action: 'sourceMode' },
    { label: '分栏模式', action: 'splitMode' },
    { label: '预览模式', action: 'previewMode' },
    { type: 'separator' },
    { label: '显示侧边栏', shortcut: '⇧⌘L', action: 'toggleSidebar' },
    {
      label: '侧边栏',
      submenu: true,
      children: [
        { label: '文件', action: 'showFiles' },
        { label: '大纲', action: 'showOutline' },
      ],
    },
    { type: 'separator' },
    { label: '显示搜索', shortcut: '⇧⌘F', action: 'showSearch' },
    { label: '专注模式', shortcut: 'F8', action: 'focusMode' },
    { label: '打字机模式', shortcut: 'F9', action: 'typewriterMode' },
    { label: '显示状态栏', action: 'statusBar' },
    { type: 'separator' },
    { label: '实际大小', shortcut: '⇧⌘9', action: 'actualSize' },
    { label: '放大', shortcut: '⇧⌘=', action: 'zoomIn' },
    { label: '缩小', shortcut: '⇧⌘-', action: 'zoomOut' },
    { type: 'separator' },
    { label: '开发者工具', shortcut: '⇧F12', action: 'devTools' },
  ],
  '主题': [
    { label: 'MiaoYan（妙言）', action: 'themeMiaoyan' },
    { label: 'Inkstone Light', action: 'themeInkstone' },
    { label: 'Slate Manual', action: 'themeSlate' },
    { label: 'Mono Lab', action: 'themeMono' },
    { label: 'Nocturne Dark', action: 'themeNocturne' },
  ],
  '窗口': [
    { label: '最小化', shortcut: '⌘M', action: 'minimize' },
    { label: '切换全屏', shortcut: 'F11', action: 'fullscreen' },
    { label: '保持窗口在最前端', action: 'alwaysOnTop' },
    { type: 'separator' },
    { label: '新建窗口', shortcut: '⇧⌘N', action: 'newWindow' },
  ],
  '帮助': [
    { label: 'Markdown 参考', action: 'mdReference' },
    { label: '键盘快捷键', action: 'showShortcuts' },
    { type: 'separator' },
    { label: 'GitHub 仓库', action: 'github' },
    { label: '反馈问题', action: 'feedback' },
    { type: 'separator' },
    { label: '关于 Prism', action: 'about' },
  ],
};
